ALTER TABLE shadow_profiles
ADD COLUMN IF NOT EXISTS daemon_accuracy    INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS kernel_access_prev INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS daemon_accuracy_prev INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS decoded_lines_prev INT NOT NULL DEFAULT 0;
