// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_responses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getResponsesForDate = `-- name: GetResponsesForDate :many
SELECT id, user_id, fragment_id, fragment_type, response_data, session_date, responded_at FROM card_responses
WHERE user_id = $1 AND session_date = $2
ORDER BY responded_at ASC
`

type GetResponsesForDateParams struct {
	UserID      uuid.UUID
	SessionDate pgtype.Date
}

func (q *Queries) GetResponsesForDate(ctx context.Context, arg GetResponsesForDateParams) ([]CardResponse, error) {
	rows, err := q.db.Query(ctx, getResponsesForDate, arg.UserID, arg.SessionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardResponse
	for rows.Next() {
		var i CardResponse
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FragmentID,
			&i.FragmentType,
			&i.ResponseData,
			&i.SessionDate,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCardResponse = `-- name: InsertCardResponse :exec
INSERT INTO card_responses (user_id, fragment_id, fragment_type, response_data, session_date)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCardResponseParams struct {
	UserID       uuid.UUID
	FragmentID   string
	FragmentType string
	ResponseData []byte
	SessionDate  pgtype.Date
}

func (q *Queries) InsertCardResponse(ctx context.Context, arg InsertCardResponseParams) error {
	_, err := q.db.Exec(ctx, insertCardResponse,
		arg.UserID,
		arg.FragmentID,
		arg.FragmentType,
		arg.ResponseData,
		arg.SessionDate,
	)
	return err
}
