// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardResponse struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	FragmentID   string
	FragmentType string
	ResponseData []byte
	SessionDate  pgtype.Date
	RespondedAt  pgtype.Timestamptz
}

type MoodLog struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	MoodScore int32
	Note      pgtype.Text
	LoggedAt  pgtype.Timestamptz
	LogDate   pgtype.Date
}

type PatternLibrary struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          pgtype.Text
	State         string
	Strength      int32
	Unnamed       bool
	FirstDetected pgtype.Date
	LastSeen      pgtype.Date
	DaemonNote    pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ShadowProfile struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	PrimaryArchetype string
	SignalConfidence pgtype.Numeric
	KernelAccess     int32
	Stage            string
	Posture          pgtype.Numeric
	Environment      string
	Texture          string
	FragmentsDecoded int32
	CompileCount     int32
	AnalystNotes     pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID                 uuid.UUID
	Email              string
	PasswordHash       string
	Timezone           string
	OnboardingComplete bool
	PushEndpointID     pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
