// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardResponse struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	FragmentID   string             `json:"fragment_id"`
	FragmentType string             `json:"fragment_type"`
	ResponseData []byte             `json:"response_data"`
	SessionDate  pgtype.Date        `json:"session_date"`
	RespondedAt  pgtype.Timestamptz `json:"responded_at"`
}

type MoodLog struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	MoodScore int32              `json:"mood_score"`
	Note      pgtype.Text        `json:"note"`
	LoggedAt  pgtype.Timestamptz `json:"logged_at"`
	LogDate   pgtype.Date        `json:"log_date"`
}

type PatternLibrary struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Name          pgtype.Text        `json:"name"`
	State         string             `json:"state"`
	Strength      int32              `json:"strength"`
	Unnamed       bool               `json:"unnamed"`
	FirstDetected pgtype.Date        `json:"first_detected"`
	LastSeen      pgtype.Date        `json:"last_seen"`
	DaemonNote    pgtype.Text        `json:"daemon_note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ShadowProfile struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	PrimaryArchetype string             `json:"primary_archetype"`
	SignalConfidence pgtype.Numeric     `json:"signal_confidence"`
	KernelAccess     int32              `json:"kernel_access"`
	Stage            string             `json:"stage"`
	Posture          pgtype.Numeric     `json:"posture"`
	Environment      string             `json:"environment"`
	Texture          string             `json:"texture"`
	FragmentsDecoded int32              `json:"fragments_decoded"`
	CompileCount     int32              `json:"compile_count"`
	AnalystNotes        pgtype.Text        `json:"analyst_notes"`
	PollyVoice          pgtype.Text        `json:"polly_voice"`
	DaemonAccuracy      int32              `json:"daemon_accuracy"`
	KernelAccessPrev    int32              `json:"kernel_access_prev"`
	DaemonAccuracyPrev  int32              `json:"daemon_accuracy_prev"`
	DecodedLinesPrev    int32              `json:"decoded_lines_prev"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Timezone           string             `json:"timezone"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	PushEndpointID     pgtype.Text        `json:"push_endpoint_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
