// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mood_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMoodLogsForDate = `-- name: GetMoodLogsForDate :many
SELECT id, user_id, mood_score, note, logged_at, log_date FROM mood_logs
WHERE user_id = $1 AND log_date = $2
ORDER BY logged_at ASC
`

type GetMoodLogsForDateParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

func (q *Queries) GetMoodLogsForDate(ctx context.Context, arg GetMoodLogsForDateParams) ([]MoodLog, error) {
	rows, err := q.db.Query(ctx, getMoodLogsForDate, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoodLog
	for rows.Next() {
		var i MoodLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MoodScore,
			&i.Note,
			&i.LoggedAt,
			&i.LogDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMoodLog = `-- name: InsertMoodLog :exec
INSERT INTO mood_logs (user_id, mood_score, note, log_date)
VALUES ($1, $2, $3, $4)
`

type InsertMoodLogParams struct {
	UserID    uuid.UUID
	MoodScore int32
	Note      pgtype.Text
	LogDate   pgtype.Date
}

func (q *Queries) InsertMoodLog(ctx context.Context, arg InsertMoodLogParams) error {
	_, err := q.db.Exec(ctx, insertMoodLog,
		arg.UserID,
		arg.MoodScore,
		arg.Note,
		arg.LogDate,
	)
	return err
}
