// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pattern_library.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPatternLibrary = `-- name: GetPatternLibrary :many
SELECT id, user_id, name, state, strength, unnamed, first_detected, last_seen, daemon_note, created_at, updated_at FROM pattern_library
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetPatternLibrary(ctx context.Context, userID uuid.UUID) ([]PatternLibrary, error) {
	rows, err := q.db.Query(ctx, getPatternLibrary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatternLibrary
	for rows.Next() {
		var i PatternLibrary
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.State,
			&i.Strength,
			&i.Unnamed,
			&i.FirstDetected,
			&i.LastSeen,
			&i.DaemonNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPattern = `-- name: InsertPattern :one
INSERT INTO pattern_library (user_id, name, state, strength, unnamed, first_detected, daemon_note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, state, strength, unnamed, first_detected, last_seen, daemon_note, created_at, updated_at
`

type InsertPatternParams struct {
	UserID        uuid.UUID
	Name          pgtype.Text
	State         string
	Strength      int32
	Unnamed       bool
	FirstDetected pgtype.Date
	DaemonNote    pgtype.Text
}

func (q *Queries) InsertPattern(ctx context.Context, arg InsertPatternParams) (PatternLibrary, error) {
	row := q.db.QueryRow(ctx, insertPattern,
		arg.UserID,
		arg.Name,
		arg.State,
		arg.Strength,
		arg.Unnamed,
		arg.FirstDetected,
		arg.DaemonNote,
	)
	var i PatternLibrary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.Strength,
		&i.Unnamed,
		&i.FirstDetected,
		&i.LastSeen,
		&i.DaemonNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePattern = `-- name: UpdatePattern :one
UPDATE pattern_library
SET name        = $2,
    state       = $3,
    strength    = $4,
    unnamed     = $5,
    last_seen   = $6,
    daemon_note = $7,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, user_id, name, state, strength, unnamed, first_detected, last_seen, daemon_note, created_at, updated_at
`

type UpdatePatternParams struct {
	ID         uuid.UUID
	Name       pgtype.Text
	State      string
	Strength   int32
	Unnamed    bool
	LastSeen   pgtype.Date
	DaemonNote pgtype.Text
}

func (q *Queries) UpdatePattern(ctx context.Context, arg UpdatePatternParams) (PatternLibrary, error) {
	row := q.db.QueryRow(ctx, updatePattern,
		arg.ID,
		arg.Name,
		arg.State,
		arg.Strength,
		arg.Unnamed,
		arg.LastSeen,
		arg.DaemonNote,
	)
	var i PatternLibrary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.Strength,
		&i.Unnamed,
		&i.FirstDetected,
		&i.LastSeen,
		&i.DaemonNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
