// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shadow_profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShadowProfile = `-- name: CreateShadowProfile :one
INSERT INTO shadow_profiles (user_id)
VALUES ($1)
RETURNING id, user_id, primary_archetype, signal_confidence, kernel_access, stage, posture, environment, texture, fragments_decoded, compile_count, analyst_notes, updated_at
`

func (q *Queries) CreateShadowProfile(ctx context.Context, userID uuid.UUID) (ShadowProfile, error) {
	row := q.db.QueryRow(ctx, createShadowProfile, userID)
	var i ShadowProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PrimaryArchetype,
		&i.SignalConfidence,
		&i.KernelAccess,
		&i.Stage,
		&i.Posture,
		&i.Environment,
		&i.Texture,
		&i.FragmentsDecoded,
		&i.CompileCount,
		&i.AnalystNotes,
		&i.UpdatedAt,
	)
	return i, err
}

const getShadowProfile = `-- name: GetShadowProfile :one
SELECT id, user_id, primary_archetype, signal_confidence, kernel_access, stage, posture, environment, texture, fragments_decoded, compile_count, analyst_notes, updated_at FROM shadow_profiles WHERE user_id = $1
`

func (q *Queries) GetShadowProfile(ctx context.Context, userID uuid.UUID) (ShadowProfile, error) {
	row := q.db.QueryRow(ctx, getShadowProfile, userID)
	var i ShadowProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PrimaryArchetype,
		&i.SignalConfidence,
		&i.KernelAccess,
		&i.Stage,
		&i.Posture,
		&i.Environment,
		&i.Texture,
		&i.FragmentsDecoded,
		&i.CompileCount,
		&i.AnalystNotes,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShadowProfile = `-- name: UpdateShadowProfile :one
UPDATE shadow_profiles
SET primary_archetype  = $2,
    signal_confidence  = $3,
    kernel_access      = $4,
    stage              = $5,
    posture            = $6,
    environment        = $7,
    texture            = $8,
    fragments_decoded  = $9,
    compile_count      = $10,
    analyst_notes      = $11,
    updated_at         = NOW()
WHERE user_id = $1
RETURNING id, user_id, primary_archetype, signal_confidence, kernel_access, stage, posture, environment, texture, fragments_decoded, compile_count, analyst_notes, updated_at
`

type UpdateShadowProfileParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	PrimaryArchetype string         `json:"primary_archetype"`
	SignalConfidence pgtype.Numeric `json:"signal_confidence"`
	KernelAccess     int32          `json:"kernel_access"`
	Stage            string         `json:"stage"`
	Posture          pgtype.Numeric `json:"posture"`
	Environment      string         `json:"environment"`
	Texture          string         `json:"texture"`
	FragmentsDecoded int32          `json:"fragments_decoded"`
	CompileCount     int32          `json:"compile_count"`
	AnalystNotes     pgtype.Text    `json:"analyst_notes"`
}

func (q *Queries) UpdateShadowProfile(ctx context.Context, arg UpdateShadowProfileParams) (ShadowProfile, error) {
	row := q.db.QueryRow(ctx, updateShadowProfile,
		arg.UserID,
		arg.PrimaryArchetype,
		arg.SignalConfidence,
		arg.KernelAccess,
		arg.Stage,
		arg.Posture,
		arg.Environment,
		arg.Texture,
		arg.FragmentsDecoded,
		arg.CompileCount,
		arg.AnalystNotes,
	)
	var i ShadowProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PrimaryArchetype,
		&i.SignalConfidence,
		&i.KernelAccess,
		&i.Stage,
		&i.Posture,
		&i.Environment,
		&i.Texture,
		&i.FragmentsDecoded,
		&i.CompileCount,
		&i.AnalystNotes,
		&i.UpdatedAt,
	)
	return i, err
}
