// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, timezone)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, timezone, onboarding_complete, push_endpoint_id, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.OnboardingComplete,
		&i.PushEndpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllActiveUsers = `-- name: GetAllActiveUsers :many
SELECT id, timezone FROM users WHERE onboarding_complete = TRUE
`

type GetAllActiveUsersRow struct {
	ID       uuid.UUID `json:"id"`
	Timezone string    `json:"timezone"`
}

func (q *Queries) GetAllActiveUsers(ctx context.Context) ([]GetAllActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveUsersRow
	for rows.Next() {
		var i GetAllActiveUsersRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, timezone, onboarding_complete, push_endpoint_id, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.OnboardingComplete,
		&i.PushEndpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, timezone, onboarding_complete, push_endpoint_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.OnboardingComplete,
		&i.PushEndpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOnboardingComplete = `-- name: UpdateOnboardingComplete :exec
UPDATE users SET onboarding_complete = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateOnboardingComplete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateOnboardingComplete, id)
	return err
}
